---
title: "R Notebook"

---

# import libraries

```{r}
library(forestplot)
library(lubridate)
library(hablar)
library(ggfortify)
library(fmsb)
library(here)
library(tidyr)
library(dplyr)
select = dplyr::select
source("./scripts/iptwhelper.R")
source("./scripts/helper.R")
```

# propensity and IPTW by weightit

```{r}
ip.iptw = ip.id %>%
  left_join(ip.sexage) %>%
  filter(!is.na(Sex) | !is.na(age)) %>%
  left_join(ip.sdi) %>%
  filter(!is.na(sdi_q)) %>%
  left_join(ip.culture) %>%
  left_join(ip.drug.all) %>%
  left_join(ip.diag)

ip.iptw = ip.iptw %>% 
  # left join paxlovid
  left_join(ip.paxlovid) %>% 
  # impute paxlovid without 4d rule
  # impute paxlovid with 4d rule
  mutate(paxlovidlong = ifelse(!is.na(daystillpaxlovid), 1, 0),
         paxlovidshort = ifelse(daystillpaxlovid <= 4, 1, 0)) %>%
  # left join molnupiravir
  left_join(ip.molnupiravir) %>%
  # impute molnupiravir without 4d rule
  # impute molnupiravir with 4d rule
  mutate(molnupiravirlong = ifelse(!is.na(daystillmolnupiravir), 1, 0),
         molnupiravirshort = ifelse(daystillmolnupiravir <= 4, 1, 0)) %>%
  filter(!(molnupiravirlong == 1 & paxlovidlong == 1))

# subset factors
x_factors_tableone = colnames(ip.iptw)
x_factors_tableone = x_factors_tableone[!x_factors_tableone %in% c("Reference Key","HN Number",
                                        "Admission Date (yyyy-mm-dd)","Discharge Date (yyyy-mm-dd)",
                                        "age_grp5", "dexamethasone", "baricitinib", "parkinsons", "district", "culture")]
x_factors_tableone = x_factors_tableone[!grepl("paxlovid|molnupiravir", x_factors_tableone)]
x_factors = x_factors_tableone[x_factors_tableone != "age"]
x_factors_weighting = x_factors

# trt_factors = c("paxlovid","molnupiravir")

# # check if there is any NA, missing data
ip.iptw %>% filter(if_any(everything(), is.na))

ip.iptw = ip.iptw %>%
  mutate(across(c(x_factors), ~replace_na(., 0)),
         across(c(x_factors) & !"age", factor)) 

# check if there is any NA, missing data
# select(ip.iptw.p.mortality, death28d, resp_death, daystillevent) %>% 
#   filter(if_any(c("death28d", "resp_death", "daystillevent"), is.na))
```

# 2 cohorts

```{r}
ip.iptw.p = ip.iptw %>%
  # remove all molnupiravir
  filter(molnupiravirlong != 1) %>%
  # remove all taken paxlovid only after 4d since admission
  filter(!(paxlovidlong == 1 & paxlovidshort != 1)) %>%
  mutate(paxlovid = ifelse(is.na(paxlovidshort), 0, 1)) %>%
  select(-contains("long"), -contains("short"), -contains("days"))

# iptw

weights.p = iptw_tableone(df = ip.iptw.p, 
              treatment = "paxlovid",
              x_factors = x_factors,
              x_factors_tableone = x_factors_tableone,
              output = F,
              path_of_unweighted_tableone = "./p.unweighted.tableone.xlsx",
              path_of_weighted_tableone = "./p.weighted.tableone.xlsx")

ip.iptw.p = ip.iptw.p %>%
  mutate(weight = weights.p$weights)

# writexl::write_xlsx(ip.iptw.p, "./ip.iptw.p.nooutcome.xlsx")

# ---------
# molnupiravir

ip.iptw.m = ip.iptw %>%
  # remove all paxlovid
  filter(paxlovidlong != 1) %>%
  # remove all taken molnupiravir only after 4d since admission
  filter(!(molnupiravirlong == 1 & molnupiravirshort != 1))%>%
  mutate(molnupiravir = ifelse(is.na(molnupiravirshort), 0, 1))%>%
  select(-contains("long"), -contains("short"), -contains("days"))

# iptw 

weights.m = iptw_tableone(df = ip.iptw.m, 
              treatment = "molnupiravir",
              x_factors = x_factors,
              x_factors_tableone = x_factors_tableone,
              output = F,
              path_of_unweighted_tableone = "./m.unweighted.tableone.xlsx",
              path_of_weighted_tableone = "./m.weighted.tableone.xlsx")

ip.iptw.m = ip.iptw.m %>%
  mutate(weight = weights.m$weights)

# mortality
# ---------
ip.iptw.p.mortality = ip.iptw.p %>%
  left_join(ip.death)

ip.iptw.p.mortality = readxl::read_xlsx(here("./covid_antiviral/data/ip.iptw.mortality.p.culture_positive_incl.xlsx"))

ip.iptw.m.mortality = ip.iptw.m %>%
  left_join(ip.death)

ip.iptw.m.mortality = readxl::read_xlsx(here("./covid_antiviral/data/ip.iptw.mortality.m.culture_positive_incl.xlsx"))

writexl::write_xlsx(ip.iptw.m.mortality, path = "./ip.iptw.mortality.m.xlsx")

# check NA
ip.iptw.m.mortality %>%
# select(ip.iptw.m.mortality, death28d, resp_death, daystillevent) %>% 
  filter(across(everything(), is.na))
```

# organ dysfunction df (original)

```{r}
ip.iptw.p.organ_dys.orig = ip.iptw.p %>%
    left_join(organ_dys) %>%
  # left-join dexamethasone 
    left_join(dexamethasone_shortlist) %>%
  # each organ dysfuntion col becomes days till event info
    mutate(across("Circulatory.shock":"Acute.liver.impairment", 
                  # convert into days till organ dysfunction
                  # otherwise NA
                  ~ifelse(!is.na(.), 
                         ymd(.) - ymd(`Admission Date (yyyy-mm-dd)`),
                         NA)),
           # left-censor as NA for event == 0
           across("Circulatory.shock":"Acute.liver.impairment", 
                  ~ifelse(. < 0, NA, .)),
           # right-censor as NA for event == 0 imputation
           across("Circulatory.shock":"Acute.liver.impairment", 
                  ~ifelse(. > 21, NA, .))
           ) %>%
  rowwise() %>%
  mutate(
    # impute respiratory failure by ventilation OR dexamethasone
    Respiratory.failure = ifelse(!is.na(Respiratory.failure) | daystilldexa <= 21,
                                        min(Respiratory.failure, daystilldexa, na.rm = T),
                                        Respiratory.failure)) %>%
  ungroup() %>%
  # mutate(# if culture is positive => NA
  #          across("Circulatory.shock":"Acute.liver.impairment", ~ifelse(culture == 1, NA, .))) %>%
  rowwise() %>%
  mutate(composite = min_(c_across(Circulatory.shock:Acute.liver.impairment)),
         composite = ifelse(composite < 0, NA, composite),
         composite = ifelse(composite > 21, NA, composite)) %>%
  ungroup()

ip.iptw.m.organ_dys.orig = ip.iptw.m %>%
    left_join(organ_dys) %>%
  # left-join dexamethasone 
    left_join(dexamethasone_shortlist) %>%
  # each organ dysfuntion col becomes days till event info
    mutate(across("Circulatory.shock":"Acute.liver.impairment", 
                  ~ifelse(!is.na(.),
                         ymd(.) - ymd(`Admission Date (yyyy-mm-dd)`),
                         NA)),
           # left-censor as NA for event == 0
           across("Circulatory.shock":"Acute.liver.impairment", 
                  ~ifelse(. < 0, NA, .)),
           # right-censor as NA for event == 0 imputation
           across("Circulatory.shock":"Acute.liver.impairment", 
                  ~ifelse(. > 21, NA, .)),
    ) %>%
  rowwise() %>%
  mutate(
    # impute respiratory failure by ventilation OR dexamethasone
    Respiratory.failure = ifelse(!is.na(Respiratory.failure) | daystilldexa <= 21,
                                        min(Respiratory.failure, daystilldexa, na.rm = T),
                                        Respiratory.failure)) %>%
  ungroup() %>%
  # mutate(# if culture is positive => NA
  #          across("Circulatory.shock":"Acute.liver.impairment", ~ifelse(culture == 1, NA, .))) %>%
  rowwise() %>%
  mutate(composite = min_(c_across(Circulatory.shock:Acute.liver.impairment)),
         composite = ifelse(composite < 0, NA, composite),
         composite = ifelse(composite > 21, NA, composite)) %>%
  ungroup()

# writexl::write_xlsx(ip.iptw.p.organ_dys.orig, path = "./ip.iptw.p.organ_dys.culture_positive_incl.xlsx")
```


# count data

```{r}
events = c("Circulatory.shock","Respiratory.failure","Acute.kidney.injury",
                       "Coagulopathy","Acute.liver.impairment","composite")
# death vs organ dysfunction
df.holder = ip.iptw.p.organ_dys.orig %>%
                             bind_rows(filter(ip.iptw.m.organ_dys.orig, molnupiravir == 1)) %>%
                             left_join(ip.death) %>%
                             mutate(across(c(events,"death28d"), ~ifelse(. != 0, 1, 0)),
                                    across(c("molnupiravir", "paxlovid"), ~replace_na(., 0)),
                                    
                                    treatment = case_when(
                                      molnupiravir == 1~"molnupiravir",
                                      paxlovid == 1~"paxlovid",
                                      T~"no antiviral"
                                    ),
                                    across(c(events, "treatment", "death28d"), factor)) %>%
  select(-paxlovid, -molnupiravir)
# df.holder %>% count(treatment)
tab.ip.death.organ_dys = CreateTableOne(vars = events,
                           data = df.holder,
                           strata = "treatment", test = T,
                           addOverall = T)
tab.ip.death.organ_dys
tab.ip.death.organ_dys = tableone_to_xlsx(tab.ip.death.organ_dys)
writexl::write_xlsx(tab.ip.death.organ_dys, path = "./results/tab.ip.death.organ_dys.xlsx")

tab.ip.icu.organ_dys

# culture vs organ dysfunction (with culture filter off)
# remember to turn off culture filter in organ dys df imputation
tab.ip.culture.organ_dys = CreateTableOne(vars = events,
                           data = ip.iptw.p.organ_dys.orig %>%
                         mutate(across(c(events), ~ifelse(!is.na(.), 1, 0)),
                       across(c(events,"culture"), factor)),
                           strata = c("culture"), test = T)
tab.ip.culture.organ_dys = tableone_to_xlsx(tab.ip.culture.organ_dys)
writexl::write_xlsx(tab.ip.culture.organ_dys, path = "./results/tab.ip.culture.organ_dys.xlsx")

# organ dysfunction, death vs LOS
tab.ip.organ_dys.death.los = CreateTableOne(vars = c(events, daystillevent),
                           data = ip.iptw.p.organ_dys.orig %>%
                             bind_rows(filter(ip.iptw.m.organ_dys.orig, molnupiravir == 1)) %>%
                             left_join(ip.death) %>%
                             mutate(across(events, ~ifelse(!is.na(.), 1, 0)),
                                    across(events, factor)),
                           strata = c("death28d"), test = T)
tab.ip.organ_dys.death.los
tab.ip.organ_dys.death.los = tableone_to_xlsx(tab.ip.organ_dys.death.los)
writexl::write_xlsx(tab.ip.organ_dys.death.los, path = "./results/tab.ip.death.organ_dys.los.xlsx")
```


# 0-60 circulatory shock drug use and comorbs analysis

```{r}
CreateTableOne(
  data = ip.iptw.p.organ_dys.orig %>% 
  filter(age_grp5 == "(0,60]") %>% 
  filter(!is.na(Circulatory.shock)) %>% 
  select(age, antiplatelets:paxlovid), 
  strata = "paxlovid")
ip.iptw.p.organ_dys.orig %>% 
  filter(age_grp5 == "(0,60]") %>% 
  filter(!is.na(Circulatory.shock), paxlovid == 1) %>% 
  select(daystillpaxlovid, Circulatory.shock)
fit = coxph(Surv(Circulatory.shock, event) ~ paxlovid,
            data = ip.iptw.p.organ_dys.orig %>% 
  filter(age_grp5 == "(0,60]") %>%
    mutate( # invalid (beyond study period) or no -> event = 0
           event = ifelse(!is.na(!!sym(daystillevent)), 1, 0),
           # impute daystillevent NA as event = 0
           event = ifelse(is.na(!!sym(daystillevent)), 0, event)
           ),
  weights = weight
  )
test = cox.zph(fit)
print(test)
```


