---
title: "R Notebook"
output: html_notebook
---

# import libraries

```{r}
library(survival)
library(broom)
# library("survminer")
```


# 2022-04-26: episode death info is missing from hosp files; 
# please refer to data_import.Rmd for IP data import 
# check drug names (optional)

```{r}
unique(ip$`Drug Name`)[grepl("ACETYL", unique(ip$`Drug Name`))]
```

# dissociate drug use and ip data (unique by HN number)

```{r}
# specify icd9 code column index
diag_cols = 35:49

df_ip = ip %>%
  select(-`Drug Name`) %>%
  distinct() %>%
  # exclude pregnancy
  mutate(pregnancy = ifelse(if_any(diag_cols, ~between(., "630", "679.99")), T, F),
         pregnancy = ifelse(is.na(pregnancy), F, pregnancy)) %>%
  filter(!pregnancy) %>%
  select(-pregnancy)
```

# medication status

```{r}
ip_drug_use = ip %>%
  # exclude pregnancy
  mutate(pregnancy = ifelse(if_any(diag_cols, ~between(., "630", "679.99")), T, F),
         pregnancy = ifelse(is.na(pregnancy), F, pregnancy)) %>%
  filter(!pregnancy) %>%
  select(-pregnancy) %>% 
  select(`HN Number`, `Drug Name`) 

medIPdf = 
  ip_drug_use %>%
  impute_meds() %>%
  select(-`Drug Name`) %>%
  distinct()

# aggregate by HN Number, get 1 if possible
medIPdf = aggregate(medIPdf, by = list(medIPdf[, "HN Number"]), FUN = "max") %>%
  select(-Group.1)

# df_ip = df_ip %>% 
#   left_join(medIPdf, by = "HN Number")
```

# comorbs

```{r}
# specify icd9 code column index
diag_cols = 35:49

ip_diag = df_ip %>% 
  select(`HN Number`, diag_cols) 

diag_cols = diag_cols - 33 
ip_diag = ip_diag %>%
  mutate(
  diabetes = ifelse(if_any(diag_cols, ~grepl("^250", .)), 1, 0),
  hypertension = ifelse(if_any(diag_cols, 
                            ~between(., "401", "405.99")), 1, 0),
  stroke = ifelse(if_any(diag_cols, 
                      ~(between(., "362.3", "362.49") |
                        between(., "430", "435.99"))), 1, 0),
  heart_failure = ifelse(if_any(diag_cols, ~grepl("^428", .)), 1, 0),
  # atrial fibrillation
  atrial_fib = ifelse(if_any(diag_cols, ~grepl("^427.31", .)), 1, 0),
  parkinsons = ifelse(if_any(diag_cols, ~grepl("^332.00", .)), 1, 0),
  # schizophrenia
  schizo = ifelse(if_any(diag_cols, ~grepl("^295", .)), 1, 0),
  # liver cirrhosis
  liver = ifelse(if_any(diag_cols, 
                     ~(grepl("^571.5|^517.2|^546|^567.89|^789.59", .) |
                     between(., "456", "456.21") |
                     between(., "567", "567.21") |
                     between(., "572.2", "572.49"))), 1, 0),
  # depression
  depression = ifelse(if_any(diag_cols, 
                    ~( grepl("^300.4|^269.5", .) |
                     between(., "269.2", "260.39") |
                     between(., "309", "311"))), 1, 0),
  # chronic kidney disease
  ckd = ifelse(if_any(diag_cols, 
                     ~(grepl("^593.9|^592", .) |
                     between(., "583", "586.99"))), 1, 0),
  # rheumatoid arthritis
  arthritis = ifelse(if_any(diag_cols, 
                         ~(grepl(., "^446.5|^725") |
                         between(., "714", "714.29") |
                         between(., "714.8", "718.89")))
                         , 1, 0),
  # obesity
  obesity =  ifelse(if_any(diag_cols, 
                     ~between(., "277.70", "280.09")), 1, 0),
  # alcohol abuse
  alcohol_abuse = ifelse(if_any(diag_cols, 
                             ~grepl("^303|^305", .)), 1, 0),
  
)
# specify binary comorbity column index
comorb_cols = 1:12 + max(diag_cols)
# replace NA as 0
ip_diag = ip_diag %>% 
  mutate_at(comorb_cols, ~replace_na(., 0))
# remove icd codes from df_diag
ip_diag = ip_diag %>%
  select(-diag_cols)

```



```{r}
ip_first_by_patient_id = df_ip %>%
  select(`Reference Key`, `HN Number`, `Admission Date (yyyy-mm-dd)`) %>%
  group_by(`Reference Key`) %>%
  slice(which.min(ymd(`Admission Date (yyyy-mm-dd)`))) %>%
  ungroup()
```


# table 1 SMD

```{r}
# hhttps://cran.r-project.org/web/packages/tableone/vignettes/smd.html#:~:text=The%20standardized%20(mean)%20difference%20is,and%20after%20propensity%20score%20matching.
library(tableone)
ip_tab1_df = df_ip %>%
  mutate(`Admission Age (Year) (episode based)` = as.numeric(`Admission Age (Year) (episode based)`),
         ) %>%
  select(`Reference Key`, `HN Number`,`Admission Date (yyyy-mm-dd)`,
         `Admission Age (Year) (episode based)`, Sex) %>%
  filter(`HN Number` %in% ip_first_by_patient_id$`HN Number`) %>%
  # left_join ip_diag to df_ip by HN Number
  left_join(., ip_diag, by = "HN Number") 

# combine with OP meds status (incomplete)
# 1. match by reference key &
# 2. appointment date <= (first) admission date
medOPdf_shortlist = ip_tab1_df %>%
  select(`Reference Key`, `Admission Date (yyyy-mm-dd)`) %>%
  left_join(medOPdf, by = "Reference Key") %>%
  filter(ymd(`Appointment Date (yyyy-mm-dd)`) <= ymd(`Admission Date (yyyy-mm-dd)`)) %>%
  select(c("Reference Key", "paxlovid", "aspirin", "ace_inhibitors", "beta_blockers", "calcium_channel_blockers", "statins", "molnupiravir"))

medIPdf_shortlist = ip_tab1_df %>%
  select(`Reference Key`, `HN Number`) %>%
  left_join(medIPdf, by = "HN Number")

common_cols = intersect(colnames(medOPdf_shortlist), colnames(medIPdf_shortlist))
medIOPdf = bind_rows(medOPdf_shortlist %>% select(common_cols), 
                     medIPdf_shortlist %>% select(common_cols))

# aggregate medIOPdf
medIOPdf = aggregate(medIOPdf, by = list(medIOPdf[, "Reference Key"]), FUN = "max") %>%
  select(-Group.1)

ip_tab1_df = ip_tab1_df %>%
  left_join(medIPdf_shortlist, by = "Reference Key")

# optional, IP data only
ip_tab1_df = ip_tab1_df %>%
  left_join(medIPdf_shortlist)

# write excel by episodes data
writexl::write_xlsx(ip_tab1_dfholder, path = "./ip_op_meds_reconciled_covid_admitted.xlsx")


# as.factor cateogorical cols
ip_tab1_dfholder = ip_tab1_df %>%
  select(-`Reference Key`, -`HN Number`, -`Admission Date (yyyy-mm-dd)`) %>%
  mutate(across(2:length(colnames(ip_tab1_dfholder)), factor))

ip_tab1_p = CreateTableOne(data = ip_tab1_dfholder, strata = "paxlovid")
ip_tab1_p
ip_tab1_m = CreateTableOne(data = ip_tab1_dfholder, strata = "molnupiravir")
ip_tab1_m
```

# 28d mortality and length of stay

```{r}
# subselect relevant cols
ip_death_los = df_ip %>%
  select(
         # keys
         `Reference Key`, `HN Number`, 
         # death information, death if discharge status == death, discharge date becomes death date
         `Admission Date (yyyy-mm-dd)`, `Discharge Date (yyyy-mm-dd)`,  `Discharge Status`, 
         # length of stay LOS in days
         `Length of Stay`
         ) %>%
  filter(ymd(`Admission Date (yyyy-mm-dd)`) >= "2022-02-16" & ymd(`Admission Date (yyyy-mm-dd)`) <= "2022-03-31")  %>% 
  # left_join with table 1 data
  # select(`HN Number`, `Length of Stay`, death28d, daystilldeath) %>%
  left_join(ip_tab1_df, .)

# impute 28d death
ip_death_los = ip_death_los %>%
  mutate(death28d = ifelse(`Discharge Status`=="DEATH" & 
                             ymd(`Discharge Date (yyyy-mm-dd)`) - ymd(`Admission Date (yyyy-mm-dd)`) <= 28 &
                             !is.na(`Discharge Status`), 1, 0),
         daystilldeath = ymd(`Discharge Date (yyyy-mm-dd)`) - ymd(`Admission Date (yyyy-mm-dd)`),
         # right-censor
         daystilldeath = ifelse(daystilldeath > 28, 28, daystilldeath),
         # replace na with 0
         daystilldeath = ifelse(is.na(daystilldeath), 0, daystilldeath))

# select only sex, age, obesity, diabetes, paxlovid and molnupiravir
ip_death_los = ip_death_los %>% 
  select(daystilldeath, death28d, Sex, `Admission Age (Year) (episode based)`, obesity, diabetes, paxlovid, molnupiravir)

# impute 65+
ip_death_los = ip_death_los %>%
  mutate(over64 = ifelse(`Admission Age (Year) (episode based)` >= 65, 1 , 0)) %>%
  select(-`Admission Age (Year) (episode based)`)
```

# table 2b descriptive 

```{r}

ip_2b = ip_death_los %>%
  select(over64, Sex, obesity, diabetes, paxlovid, molnupiravir) %>%
  mutate_all(factor)
ip_tab2b = CreateTableOne(data = ip_2b, strata = c("paxlovid"))
ip_tab2b
```

# (univariate) hazard ratio per predictor

```{r}
model = as.data.frame(c())
# iterate over cols
for(i in 3:length(ip_death_los)){
  x = colnames(ip_death_los)[i]
  iformula <- as.formula(sprintf("Surv(daystilldeath, death28d) ~ %s", x))
  coxfit_paxlovid <- coxph(formula = iformula, 
                data = ip_death_los)
  model = bind_rows(model, tidy(coxfit_paxlovid, exponentiate = T, conf.int = T, conf.level = .95))
}
model
```

# multivariate model

```{r}
coxfit_paxlovid <- coxph(formula = Surv(daystilldeath, death28d) ~ Sex+ over64+obesity+diabetes+paxlovid+molnupiravir, 
                data = ip_death_los)
tidy(coxfit_paxlovid, exponentiate = T, conf.int = T, conf.level = .95)
plot(survfit(coxfit_paxlovid))
```

# LOS

```{r}

ggplot(ip_death_los, aes(x = as.numeric(`Length of Stay`), fill = as.factor(paxlovid))) +
  geom_histogram()
```

