---
title: "R Notebook"
output: html_notebook
---

# HR organ dysfunction/mortality robust s.e./bootstrapped

```{r}
# params
x_factors_hr = c("overall", "Sex","age_grp5","sdi_q","diabetes")
# x_factors_hr = c("overall")
treatment = "antiviral"
df = ip.iptw.c.mortality
path = "./culture_results/hr/hr.mortality.c.xlsx"
# events = c("Circulatory.shock","Respiratory.failure","Acute.kidney.injury",
#                        "Coagulopathy","Acute.liver.impairment","composite")
# or 
events = c("death28d", "resp_death")
# outcome = "organ_dys"
# or
outcome = "mortality"
# _________
hr.organ_dys = c()
for(eventtype in events){
  print(eventtype)
  
  if(outcome == "mortality"){
    days_tillevent = "daystillevent"
    ip.iptw.organ_dys = df %>% 
    mutate(
           # event is directly days_tillevent or eventtype in mortality dataframes
           event = get(eventtype)
           )
    
  }else{
    days_tillevent = eventtype
    ip.iptw.organ_dys = df %>% 
    mutate(
           # invalid (beyond study period) or no -> event = 0
           event = ifelse(!is.na(!!sym(days_tillevent)), 1, 0),
           # impute days_tillevent NA as event = 0
           event = ifelse(is.na(!!sym(days_tillevent)), 0, event),
           # replace the days_tillevent column, aka organ dysfunction column NA (event == 0) with 21d
           !!(days_tillevent) := ifelse(is.na(get(days_tillevent)),
                                            21,
                                            get(days_tillevent))
           )
  }
  
  
  hr.one_eventtype = iptw_hr_tidy(df = ip.iptw.organ_dys,
                          x_factors = x_factors_hr,
                          # x_factors_weighting = x_factors_weighting,
                          event = "event",
                          daystillevent = days_tillevent,
                          treatment = treatment) %>%
    mutate(event = eventtype)
  hr.organ_dys = bind_rows(hr.organ_dys, hr.one_eventtype)
  
}
hr.organ_dys = hr.organ_dys %>%
  mutate(across(c("estimate", "conf.low", "conf.high"), function(x){signif(x, 3)})) %>%
  select(segment, event, estimate, conf.low, conf.high) %>%
  mutate(hr.text = paste0(estimate, "(", conf.low, "—", conf.high, ")")) 
# writexl::write_xlsx(hr.organ_dys, path = path)
```

# event/risk table of organ dysfunction/mortality

```{r}
# params
# --------
# x_factors_hr = c("Sex","age_grp5","sdi_q","diabetes")
# treatment = "paxlovid"
# df = ip.iptw.p.organ_dys.orig
# path = "./results/event_risk.organ_dys.p.resp_update.non_culture_positive.xlsx"
# events = c("Circulatory.shock","Respiratory.failure",
#                    "Acute.kidney.injury","Coagulopathy","Acute.liver.impairment","composite")
# # or 
# # events = c("death28d", "resp_death")
# # outcome = "mortality" 
# # or 
# outcome = "organ_dys"
# --------
x_factors_hr_orig = x_factors_hr
x_factors_hr = x_factors_hr[x_factors_hr != "overall"]
tab1.organ_dys.numerics = c()
for(eventtype in events){
  print(eventtype)
  tab1.organ_dys.one_eventtype = df %>%
      select(x_factors_hr, treatment, eventtype) 
  if(outcome != "mortality"){
    # organ dysfunction
    tab1.organ_dys.one_eventtype = tab1.organ_dys.one_eventtype %>%
      mutate(event = ifelse(!is.na(!!as.name(eventtype)), 1, 0))
  }else{
    # mortality
    tab1.organ_dys.one_eventtype = tab1.organ_dys.one_eventtype %>%
      mutate(event = !!as.name(eventtype))
  }
  # browser()
  tab1.organ_dys.one_eventtype = tab1.organ_dys.one_eventtype %>%
    mutate(across(everything(), factor)) %>%
  CreateTableOne(vars = x_factors_hr,
                 data = .,
                 strata = c(treatment, "event"),
               test = F,
               smd = F)
  
  tab1.organ_dys.one_eventtype <- print(tab1.organ_dys.one_eventtype, quote = FALSE, 
                               noSpaces = TRUE, printToggle = FALSE, 
                               smd = F, showAllLevels = T)
  tab1.organ_dys.one_eventtype = as.data.frame(cbind("variables" = rownames(tab1.organ_dys.one_eventtype),tab1.organ_dys.one_eventtype))
  # remove row names
  rownames(tab1.organ_dys.one_eventtype) = NULL 
  

  tab1.organ_dys.one_eventtype = tab1.organ_dys.one_eventtype %>% 
    # remove brackets
    mutate(across(everything(), remove_brackets_helper),
           across("0:0":"1:1", as.numeric),
           # add event type info
           event = eventtype)
  tab1.organ_dys.numerics = bind_rows(tab1.organ_dys.numerics, tab1.organ_dys.one_eventtype)
  
}
colnames(tab1.organ_dys.numerics)[3:6] = c("noevent_ctrl", "event_ctrl", "noevent_trt", "event_trt")

# for export into .xlsx
tab1.organ_dys = tab1.organ_dys.numerics %>%
    # make event/risk cols
    mutate("trt.user" = paste(event_trt , "/", event_trt + event_ctrl),
           "trt.nonuser" = paste(noevent_trt , "/", noevent_trt + noevent_ctrl)) %>%
    # discard strata info
    select(-("noevent_ctrl":"event_trt"))
## Save to a xlsx
# writexl::write_xlsx(tab1.organ_dys, path = path)

x_factors_hr = x_factors_hr_orig
```

# weighted IRD organ dysfunction/mortality, stratified and overall

```{r}
# params
# --------
# x_factors_hr = c("overall","Sex","age_grp5","sdi_q","diabetes")
# treatment = "molnupiravir"
# df = ip.iptw.m.organ_dys.orig
# path = "./results/ir.organ_dys.weighted.m.resp_failure.non_culture_positive.xlsx"
# events = c("Circulatory.shock","Respiratory.failure",
#                    "Acute.kidney.injury","Coagulopathy","Acute.liver.impairment","composite")
# or
# events = c("death28d","resp_death")
# outcome = "mortality" # or anything else for organ dysfunction
# or
# outcome = "organ_dys"
# --------
incidence.df = c()
for(eventtype in events){
  
  incidence.eventtype = c()
  
  # iterate organ dysfunction modes
  for(x in x_factors_hr){
    # x = "Sex"
    if(x == "overall"){
      group_var = c(treatment)
    }else{
      group_var = c(x, treatment)
    }
    print(x)
    # iterate segments
    # case numbers by segment
    cases.factor = df %>%
       #
      mutate(!!(eventtype) := ifelse(!is.na(get(eventtype)), 1, 0),
             # weighting
             !!(eventtype) := get(eventtype) * weight) %>%
     
      group_by_at(group_var) %>%
      # calculate # cases
      summarise(no.cases = sum(get(eventtype))) %>%
      ungroup()
    
    if(outcome != "mortality"){
      days_tillevent = eventtype
    }else{
      days_tillevent = "daystillevent"
    }
    # print(days_tillevent)
    # person-time by segment
    pt.factor = df %>%
      # weighting
      mutate(!!(days_tillevent) := as.numeric(get(days_tillevent)),
             !!(days_tillevent) := ifelse(is.na(get(days_tillevent)), 21, get(days_tillevent)),
             !!(days_tillevent) := get(days_tillevent) * weight,
             !!(treatment) := as.factor(get(treatment))) %>%
      # calculate weighted PT by segment and treatment
      group_by_at(group_var) %>%
      summarise(person_time = sum(get(days_tillevent))) %>%
      ungroup()
    
    incidence.factor = cases.factor %>% 
      mutate(across(1:2, factor)) %>%
      left_join(pt.factor) 
    # browser()
    if(x == "overall"){
      incidence.factor = incidence.factor %>% 
        mutate(segment = "overall")
      
    }else{
      incidence.factor = incidence.factor %>% 
        mutate(segment = paste0(x, !!!syms(x)))
    }
    incidence.factor = incidence.factor %>%
      mutate(event = eventtype) %>%
      select(-contains(x)) %>%
      relocate(segment, .before = !!as.name(treatment)) %>%
      mutate(across(3:4, function(x){as.numeric(as.character(x))}))
    incidence.eventtype = rbind(incidence.eventtype, incidence.factor)
  }
  incidence.df = rbind(incidence.df, incidence.eventtype)
}


incidence.df = incidence.df %>%
  pivot_wider(names_from = treatment, 
              values_from = c("no.cases", "person_time"), 
              names_glue = paste0("trt{",treatment,"}.{.value}")) %>%
  mutate(across(contains("trt"), as.numeric))

ir.df = incidence.df %>%
  mutate(trt0.ir = signif(trt0.no.cases / trt0.person_time * 1000, 3),
         trt1.ir = signif(trt1.no.cases / trt1.person_time * 1000, 3)) %>%
  select(-trt0.no.cases,-trt1.no.cases,-trt0.person_time,-trt1.person_time)

ird = ratedifference(incidence.df$"trt1.no.cases",
                     incidence.df$"trt0.no.cases",
                     incidence.df$"trt1.person_time",
                     incidence.df$"trt0.person_time", CRC = T, conf.level = .95)
ird.df = incidence.df %>%
  select(contains("segment"), event) %>%
  bind_cols(p.value = ird$p.value) %>%
  bind_cols(estimate = ird$estimate) 
conf.int = as.data.frame(matrix(ird$conf.int, ncol = 2))
colnames(conf.int) = c("conf.low", "conf.high")
ird.df = ird.df %>%
  bind_cols(conf.int) %>%
  mutate(across(estimate:conf.high, ~(.*1000)),
         # round off
         across(estimate:conf.high, function(x){signif(x, 3)}))

ird.df = ird.df %>% 
  left_join(ir.df)

ird.df = ird.df %>%
  mutate(ird.text = paste0(estimate, "(", conf.low, "-", conf.high, ")"))
# writexl::write_xlsx(ird.df, path = path)
```

# combine event/risk, ird and hr tables 

```{r}
hr.table = tab1.organ_dys %>% 
  bind_cols(select(ird.df, trt0.ir, trt1.ir, estimate:conf.high) %>%
    rename_with(.fn = ~paste0("ird.", .), .cols=estimate:conf.high)) %>%
  bind_cols(select(hr.organ_dys, estimate:conf.high)%>%
              rename_with(.fn = ~paste0("hr.", .), .cols=estimate:conf.high))
writexl::write_xlsx(hr.table, path = path)
writexl::write_xlsx(tab1.organ_dys, path = gsub(".xlsx", ".eventrisk.xlsx", path))
writexl::write_xlsx(ird.df, path = gsub(".xlsx", ".ir.xlsx", path))
writexl::write_xlsx(hr.organ_dys, path = gsub(".xlsx", ".hr.xlsx", path))
```
