---
title: "R Notebook"

---

# import libraries

```{r}
library(forestplot)
library(ggfortify)
library(fmsb)
```

# propensity and IPTW by weightit

```{r}
ip.iptw = ip.id %>%
  left_join(ip.sexage) %>%
  filter(!is.na(Sex) | !is.na(age)) %>%
  left_join(ip.sdi) %>%
  filter(!is.na(sdi_q)) %>%
  left_join(ip.drug.all) %>%
  left_join(ip.diag)

ip.iptw = ip.iptw %>% 
  # left join paxlovid
  left_join(ip.paxlovid) %>% 
  # impute paxlovid without 4d rule
  # impute paxlovid with 4d rule
  mutate(paxlovidlong = ifelse(!is.na(daystillpaxlovid), 1, 0),
         paxlovidshort = ifelse(daystillpaxlovid <= 4, 1, 0)) %>%
  # left join molnupiravir
  left_join(ip.molnupiravir) %>%
  # impute molnupiravir without 4d rule
  # impute molnupiravir with 4d rule
  mutate(molnupiravirlong = ifelse(!is.na(daystillmolnupiravir), 1, 0),
         molnupiravirshort = ifelse(daystillmolnupiravir <= 4, 1, 0)) 

# subset factors
x_factors_tableone = colnames(ip.iptw)
x_factors_tableone = x_factors_tableone[!x_factors_tableone %in% c("Reference Key","HN Number",
                                        "Admission Date (yyyy-mm-dd)","Discharge Date (yyyy-mm-dd)",
                                        "age_grp5", "dexamethasone", "baricitinib", "parkinsons", "district")]
x_factors_tableone = x_factors_tableone[!grepl("paxlovid|molnupiravir", x_factors_tableone)]
x_factors = x_factors_tableone[x_factors_tableone != "age"]

# trt_factors = c("paxlovid","molnupiravir")

# # check if there is any NA, missing data
# ip.iptw %>% filter(across(c("Sex"), is.na))

ip.iptw = ip.iptw %>%
  mutate(across(c(x_factors), ~replace_na(., 0)),
         across(c(x_factors) & !"age", factor)) 

# check if there is any NA, missing data
ip.iptw %>% filter(across(x_factors, is.na))
```

# 2 cohorts

```{r}
ip.iptw.p = ip.iptw %>%
  # remove all molnupiravir
  filter(molnupiravirlong != 1) %>%
  # remove all taken paxlovid only after 4d since admission
  filter(!(paxlovidlong == 1 & paxlovidshort != 1)) %>%
  mutate(paxlovid = ifelse(is.na(paxlovidshort), 0, 1)) %>%
  select(-contains("long"), -contains("short"), -contains("days"))

# iptw

weights.p = iptw_tableone(df = ip.iptw.p, 
              treatment = "paxlovid",
              x_factors = x_factors,
              x_factors_tableone = x_factors_tableone,
              path_of_unweighted_tableone = "./p.unweighted.tableone.xlsx",
              path_of_weighted_tableone = "./p.weighted.tableone.xlsx")

ip.iptw.p = ip.iptw.p %>%
  mutate(weight = weights.p$weights)

# writexl::write_xlsx(ip.iptw.p, "./ip.iptw.p.nooutcome.xlsx")

# ---------
# molnupiravir

ip.iptw.m = ip.iptw %>%
  # remove all paxlovid
  filter(paxlovidlong != 1) %>%
  # remove all taken molnupiravir only after 4d since admission
  filter(!(molnupiravirlong == 1 & molnupiravirshort != 1))%>%
  mutate(molnupiravir = ifelse(is.na(molnupiravirshort), 0, 1))%>%
  select(-contains("long"), -contains("short"), -contains("days"))

# iptw 

weights.m = iptw_tableone(df = ip.iptw.m, 
              treatment = "molnupiravir",
              x_factors = x_factors,
              x_factors_tableone = x_factors_tableone,
              path_of_unweighted_tableone = "./m.unweighted.tableone.xlsx",
              path_of_weighted_tableone = "./m.weighted.tableone.xlsx")

ip.iptw.m = ip.iptw.m %>%
  mutate(weight = weights.m$weights)

# ---------

# optional
# -----------
# ip.tab1.p = CreateTableOne(vars = x_factors_tableone,
#                            data = ip.iptw.p, 
#                            strata = "paxlovid", test = F)
# print(ip.tab1.p, smd = T)
# 
# 
# ip.tab1.m = CreateTableOne(vars = x_factors_tableone,
#                            data = ip.iptw.m, 
#                            strata = "molnupiravir", test = F)
# print(ip.tab1.m, smd = T)

# ip.tab1.death = CreateTableOne(data = ip.iptw %>%
#                                  left_join(ip.death) %>%
#                                  
#                              filter(!(paxlovid == 1 & molnupiravir == 1)) %>%
#                              select(x_factors, molnupiravir, paxlovid, death28d), 
#                            strata = "death28d", test = F)
# print(ip.tab1.death, smd = T)

```


# HR mortality


```{r}
x_factors_hr = c("Sex", "age_grp5", "sdi_q", "diabetes", "cancer")
# x_factors_hr2 = c("Sex", "age_grp3", "sdi_q", "diabetes", "cancer")
```

```{r}
treatment = "paxlovid"
df = ip.iptw.p
path = "./ip.iptw.p.mortality.xlsx"


ip.iptw.mortality = df  %>%
  left_join(ip.death, by = 'Reference Key') %>%
  # replace NA
  mutate(across(!"daystillevent", ~replace_na(., 0)),
         # factorise everything
         across(!"daystillevent" & !"age" & !"weight", factor))

ip.iptw.mortality.p = ip.iptw.mortality

# writexl::write_xlsx(ip.iptw.mortality, path)

for(event in c("death28d", "resp_death")){
  hr.death = c()
  hr.death = iptw_hr_tidy(df = ip.iptw.mortality,
                          x_factors = x_factors_hr,
                          event = event,
                          daystillevent = "daystillevent",
                          treatment = treatment)
  hr.death
  hr.death = hr.death %>% mutate(across(c("estimate","conf.low", "conf.high"), function(x){signif(x, 3)}))
  writexl::write_xlsx(hr.death, path = paste0("./results/hr/hr.", event, ".", treatment, ".xlsx"))
}
```


```{r}
# overall hr mortality
event = "resp_death"
iformula <- as.formula(paste("Surv(as.numeric(daystillevent),as.numeric(", event,")) ~ ", "molnupiravir", collapse = ''))
res = tidy(
  coxph(formula = iformula, 
              data = ip.iptw.mortality.m,
              weights = ip.iptw.mortality.m$weight), 
        exponentiate = T, conf.int = T, conf.level = .95)
res
```

# organ dysfunction df

```{r}
ip.iptw.p.organ_dys.orig = ip.iptw.p %>%
    left_join(organ_dys) %>%
  # each organ dysfuntion col becomes days till event info
    mutate(across("Circulatory.shock":"Acute.liver.impairment", 
                  ~ifelse(!is.na(.), 
                         ymd(.) - ymd(`Admission Date (yyyy-mm-dd)`),
                         NA)),
           # left-censor as NA for event == 0
           across("Circulatory.shock":"Acute.liver.impairment", 
                  ~ifelse(. < 0, NA, .)),
           # right-censor as NA for event == 0 imputation
           across("Circulatory.shock":"Acute.liver.impairment", 
                  ~ifelse(. > 21, NA, .)),
           ) %>%
  rowwise() %>%
  mutate(
         composite = min_(c_across(Circulatory.shock:Acute.liver.impairment)),
         composite = ifelse(composite < 0, NA, composite),
         composite = ifelse(composite > 21, NA, 0)) %>%
  ungroup()

ip.iptw.m.organ_dys.orig = ip.iptw.m %>%
    left_join(organ_dys) %>%
  # each organ dysfuntion col becomes days till event info
    mutate(across("Circulatory.shock":"Acute.liver.impairment", 
                  ~ifelse(!is.na(.), 
                         ymd(.) - ymd(`Admission Date (yyyy-mm-dd)`),
                         NA)),
           # left-censor as NA for event == 0
           across("Circulatory.shock":"Acute.liver.impairment", 
                  ~ifelse(. < 0, NA, .)),
           # right-censor as NA for event == 0 imputation
           across("Circulatory.shock":"Acute.liver.impairment", 
                  ~ifelse(. > 21, NA, .)),
           ) %>%
  rowwise() %>%
  mutate(
         composite = min_(c_across(Circulatory.shock:Acute.liver.impairment)),
         composite = ifelse(composite < 0, NA, composite),
         composite = ifelse(composite > 21, NA, 0)) %>%
  ungroup()

# writexl::write_xlsx(ip.iptw.m.organ_dys.orig, path = "./ip.iptw.m.organ_dys.orig.xlsx")
```

# HR organ dysfunction

```{r}
# params
treatment = "paxlovid"
path = "./results/hr/hr.organ_dys.agr_grp5.nofrills.p.xlsx"
df = ip.iptw.p.organ_dys.orig
# _________
hr.organ_dys = c()
for(daystillevent in c("Circulatory.shock","Respiratory.failure","Acute.kidney.injury","Coagulopathy","Acute.liver.impairment","composite")){
  
  print(daystillevent)
  # daystillevent = "Circulatory.shock"
  ip.iptw.organ_dys = df %>% 
    mutate(
           # invalid (beyond study period) or no -> event = 0
           event = ifelse(!is.na(!!sym(daystillevent)), 1, 0),
           # impute daystillevent NA as event = 0
           event = ifelse(is.na(!!sym(daystillevent)), 0, event),
           # replace the daystillevent column, aka organ dysfunction column NA (event == 0) with 21d
           !!(daystillevent) := ifelse(is.na(get(daystillevent)),
                                            21,
                                            get(daystillevent))
           )
  hr.one_eventtype = iptw_hr_tidy(df = ip.iptw.organ_dys,
                          x_factors = x_factors_hr,
                          event = "event",
                          daystillevent = daystillevent,
                          treatment = treatment) %>%
    mutate(event = daystillevent)
  hr.organ_dys = bind_rows(hr.organ_dys, hr.one_eventtype)
  
}
# overall hr organ dysfuntion
for(daystillevent in c("Circulatory.shock","Respiratory.failure",
                       "Acute.kidney.injury","Coagulopathy","Acute.liver.impairment",
                       "composite")){

  print(daystillevent)
  # daystillevent = "Circulatory.shock"
  ip.iptw.organ_dys = df %>%
    mutate(
           # invalid (beyond study period) or no -> event = 0
           event = ifelse(!is.na(!!sym(daystillevent)), 1, 0),
           # impute daystillevent NA as event = 0
           event = ifelse(is.na(!!sym(daystillevent)), 0, event),
           # replace the daystillevent column, aka organ dysfunction column NA (event == 0) with 21d
           !!(daystillevent) := ifelse(is.na(get(daystillevent)),
                                            21,
                                            get(daystillevent))
           )
  iformula <- as.formula(paste("Surv(as.numeric(",daystillevent,"),as.numeric(event)) ~ ", treatment, collapse = ''))
  hr.one_eventtype = tidy(
        coxph(formula = iformula,
              data = ip.iptw.organ_dys,
              weights = ip.iptw.organ_dys$weight),
        exponentiate = T, conf.int = T, conf.level = .95) %>%
    mutate(event = daystillevent)
  hr.organ_dys = bind_rows(hr.organ_dys, hr.one_eventtype)

}
hr.organ_dys = hr.organ_dys %>%
  mutate(across(c("estimate", "conf.low", "conf.high"), function(x){signif(x, 3)}))
writexl::write_xlsx(hr.organ_dys, path = path)
```

# event/risk table of organ dysfunction/mortality

```{r}
# params
# --------
x_factors_hr = c("Sex","age_grp5","sdi_q","diabetes","cancer")
treatment = "paxlovid"
df = ip.iptw.p.organ_dys.orig
path = "./results/event_risk.organ_dys.m.xlsx"
events = c("Circulatory.shock","Respiratory.failure",
                   "Acute.kidney.injury","Coagulopathy","Acute.liver.impairment","composite")
# or 
events = c("death28d", "resp_death")
outcome = "mortality" 
# or 
outcome = "organ_dys"
# --------
tab1.organ_dys.numerics = c()
for(eventtype in events){
  print(eventtype)
  tab1.organ_dys.one_eventtype = df %>%
      select(x_factors_hr, treatment, eventtype) 
  if(outcome != "mortality"){
    # organ dysfunction
    tab1.organ_dys.one_eventtype = tab1.organ_dys.one_eventtype %>%
      mutate(event = ifelse(!is.na(!!as.name(eventtype)), 1, 0))
  }else{
    # mortality
    tab1.organ_dys.one_eventtype = tab1.organ_dys.one_eventtype %>%
      mutate(event = !!as.name(eventtype))
  }
  # browser()
  tab1.organ_dys.one_eventtype = tab1.organ_dys.one_eventtype %>%
    mutate(across(everything(), factor)) %>%
  CreateTableOne(vars = x_factors_hr,
                 data = .,
                 strata = c(treatment, "event"),
               test = F,
               smd = F)
  
  tab1.organ_dys.one_eventtype <- print(tab1.organ_dys.one_eventtype, quote = FALSE, 
                               noSpaces = TRUE, printToggle = FALSE, 
                               smd = F, showAllLevels = T)
  tab1.organ_dys.one_eventtype = as.data.frame(cbind("variables" = rownames(tab1.organ_dys.one_eventtype),tab1.organ_dys.one_eventtype))
  # remove row names
  rownames(tab1.organ_dys.one_eventtype) = NULL 
  

  tab1.organ_dys.one_eventtype = tab1.organ_dys.one_eventtype %>% 
    # remove brackets
    mutate(across(everything(), remove_brackets_helper),
           across("0:0":"1:1", as.numeric)) %>%
    # add organ dysfunction type header info
    add_row(variables = eventtype, .before = 1) 
  tab1.organ_dys.numerics = bind_rows(tab1.organ_dys.numerics, tab1.organ_dys.one_eventtype)
  
}
colnames(tab1.organ_dys.numerics)[3:6] = c("noevent_ctrl", "event_ctrl", "noevent_trt", "event_trt")

# for export into .xlsx
tab1.organ_dys = tab1.organ_dys.numerics%>%
    # make event/risk cols
    mutate("trt.user" = paste(event_trt , "/", event_trt + event_ctrl),
           "trt.nonuser" = paste(noevent_trt , "/", noevent_trt + noevent_ctrl)) %>%
    # discard strata info
    select(-("noevent_ctrl":"event_trt"))
## Save to a xlsx
writexl::write_xlsx(tab1.organ_dys, path = path)


```

# weighted IRD organ dysfunction/mortality, stratified and overall

```{r}
# params
# --------
x_factors_hr = c("Sex","age_grp5","sdi_q","diabetes","cancer","overall")
treatment = "molnupiravir"
df = ip.iptw.mortality.m
path = "./results/ird.organ_dys.weighted.nofrills.m.xlsx"
events = c("Circulatory.shock","Respiratory.failure",
                   "Acute.kidney.injury","Coagulopathy","Acute.liver.impairment","composite")
# or
events = c("death28d","resp_death")
outcome = "mortality" # or anything else for organ dysfunction
# --------
incidence.df = c()
for(eventtype in events){
  
  incidence.eventtype = c()
  
  # iterate organ dysfunction modes
  for(x in x_factors_hr){
    if(x == "overall"){
      group_var = c(treatment)
    }else{
      group_var = c(x, treatment)
    }
    print(x)
    # iterate segments
    # case numbers by segment
    cases.factor = df %>%
       #
      mutate(!!(eventtype) := ifelse(!is.na(get(eventtype)), 1, 0),
             # weighting
             !!(eventtype) := get(eventtype) * weight) %>%
     
      group_by_at(group_var) %>%
      # calculate # cases
      summarise(no.cases = sum(get(eventtype))) %>%
      ungroup()
    
    if(outcome != "mortality"){
      days_tillevent = eventtype
    }else{
      days_tillevent = "daystillevent"
    }
    # print(days_tillevent)
    # person-time by segment
    pt.factor = df %>%
      # weighting
      mutate(!!(days_tillevent) := as.numeric(get(days_tillevent)),
             !!(days_tillevent) := ifelse(is.na(get(days_tillevent)), 21, get(days_tillevent)),
             !!(days_tillevent) := get(days_tillevent) * weight,
             !!(treatment) := as.factor(get(treatment))) %>%
      # calculate weighted PT by segment and treatment
      group_by_at(group_var) %>%
      summarise(person_time = sum(get(days_tillevent))) %>%
      ungroup()
    
    incidence.factor = cases.factor %>% 
      mutate(across(1:2, factor)) %>%
      left_join(pt.factor) 
    if(x == "overall"){
      incidence.factor = incidence.factor %>% 
        mutate(segment = "overall")
      
    }else{
      incidence.factor = incidence.factor %>% 
        mutate(segment = paste0(x, !!!syms(x)))
    }
    incidence.factor = incidence.factor %>%
      mutate(event = eventtype) %>%
      select(-contains(x)) %>%
      relocate(segment, .before = !!as.name(treatment)) 
    incidence.eventtype = rbind(incidence.eventtype, incidence.factor)
  }
  incidence.df = rbind(incidence.df, incidence.eventtype)
}


incidence.df = incidence.df %>%
  pivot_wider(names_from = treatment, 
              values_from = c("no.cases", "person_time"), 
              names_glue = paste0("trt{",treatment,"}.{.value}")) %>%
  mutate(across(!"event" & !"segment", as.numeric))



ird = ratedifference(incidence.df$"trt1.no.cases", 
                     incidence.df$"trt0.no.cases", 
                     incidence.df$"trt1.person_time", 
                     incidence.df$"trt0.person_time", CRC = T, conf.level = .95)
ird.df = incidence.df %>%
  select(contains("segment"), event) %>%
  bind_cols(p.value = ird$p.value) %>%
  bind_cols(estimate = ird$estimate) 
conf.int = as.data.frame(matrix(ird$conf.int, ncol = 2))
colnames(conf.int) = c("conf.low", "conf.high")
ird.df = ird.df %>%
  bind_cols(conf.int) %>%
  mutate(across(estimate:conf.high, ~(.*1000)),
         # round off
         across(estimate:conf.high, function(x){signif(x, 3)}))

writexl::write_xlsx(ird.df, path = path)
```


# forest plot

```{r}
unique(hr.organ_dys.p$event)

hr.organ_dys %>%
    filter(event == "Respiratory.failure",
           segment != "age_grp5NA") %>%
    # group_by(event) %>%
    forestplot(labeltext = segment,
              mean = estimate,
              lower = conf.low,
              upper = conf.high,
              clip = c(.1, 10),
              xticks=c(.1, 1, 10),
              xlog = T,
              zero = 1) 

```


# 0-60 circulatory shock drug use and comorbs analysis

```{r}
CreateTableOne(
  data = ip.iptw.p.organ_dys.orig %>% 
  filter(age_grp5 == "(0,60]") %>% 
  filter(!is.na(Circulatory.shock)) %>% 
  select(age, antiplatelets:paxlovid), 
  strata = "paxlovid")
ip.iptw.p.organ_dys.orig %>% 
  filter(age_grp5 == "(0,60]") %>% 
  filter(!is.na(Circulatory.shock), paxlovid == 1) %>% 
  select(daystillpaxlovid, Circulatory.shock)
fit = coxph(Surv(Circulatory.shock, event) ~ paxlovid,
            data = ip.iptw.p.organ_dys.orig %>% 
  filter(age_grp5 == "(0,60]") %>%
    mutate( # invalid (beyond study period) or no -> event = 0
           event = ifelse(!is.na(!!sym(daystillevent)), 1, 0),
           # impute daystillevent NA as event = 0
           event = ifelse(is.na(!!sym(daystillevent)), 0, event)
           ),
  weights = weight
  )
test = cox.zph(fit)
print(test)
```


