---
title: "meds"
---

# import helper functions

```{r}
source("./scripts/helper.R")
```

# all drugs except bronchodilators and inhaled corticosteroids, and cancer drugs (ip.drug.imputed)

```{r}
meds_dict_untidy <- tribble(
        ~drug.cat, ~drug.name,
        # antiplatelets
        "antiplatelets","Aspirin
Ticlopidine, Clopidogrel, Prasugrel, Ticagrelor, Cangrelor, 
Abciximab, Eptifibatide, Tirofiban
Dipyridamole, Cilostazol

Warfarin, Heparin
Rivaroxaban, Dabigatran,Apixaban,Edoxaban,Enoxaparin,Fondaparinux",

        # ace inhibitors
        "ace_inhibitors", "Benazepril, Captopril, Clizapril, Enalapril, Enalaprilat, Fosinopril, Lisinopril, Moexipril, Perindopril, Quinapril, Ramipril, Trandolapril
Azilsartan, Candesartan, Eprosartan, Irbesartan, Losartan, Olmesartan, Telmisartan, Valsartan
",

        # beta blockers
        "beta_blockers", "Acebutalol, Atenolol, Betaxolol, Bisoprolol, Carteolol, Carvedilol, Esmolol, Labetalol, Levobunolol, Metoprolol, Nadolol, Nebivolol, Pindolol, Propanolol, Sotalol, Timolol",
        # calcium channel blockers
        "calcium_channel_blockers", "Amlodipine, Clevidipine, Felodipine, Flunarzine, Isradipine, Levamlodipine, Nicardipine, Nifedipine, Verapamil, Diltiaze", 

        # diuretics
        "diuretics", "Bendroflumethiazide, Chlorothiazide, Chlortalidone, Cyclopenthiazide, Hydrochlorothiazide, Indapamide, Metolazone, Poluthiazide, Xipamide, Bumetanide, Furosemide, Lasix, Torasemide, Amiloride, Eplerenone, Spironolactone, Triamterene, Amilozide, Amilofruse, Triamterzide, Mannitol",
        
        # statins
        "statins", "Atorvastatin, Simvastatin, Fluvastatin, Lovastatin, Pitavastatin, Pravastatin, Rosuvastatin",

        # system corticosteroids
        "sys_corticosteroids", "Prednisolone, Hydrocortisone, Dexamethasone, Fludrocortisone, Triamcinolone, Methylprednisolone",

        # antidiabetics
        "antidiabetics", "Canagliflozin, dapagliflozin, empagliflozin,Chlorpropamide, glimepiride, glipizide, glyburide, tolazamide, tolbutamide
Rosiglitazone, pioglitazone, Metformin, Nateglinide, repaglinide, Insulin, albiglutide, dulaglutide, exenatide, liraglutide, lixisenatide, pramlintide, Alogliptan, linagliptan, saxagliptin, sitagliptin

Acarbose, migiltol",
        
        # rheumatoid
        "rheumatoid", "Allopurinol, Colchicine, Hydroxychloroquine, Sulfasalazine, Febuxostat, Rasburicase, Leflunomide, Baricitinib, Certolizumab, Tofacitinib, Etanercept, Tocilizumab, Adalimumab, Probenecid, Ixekizumab, Secukinumab, Ustekinumab, Belimumab, Golimumab",

)
```

# impute the mentioned drugs

```{r}
# make a medication dictionary with drug categories and drug names, names separated by comma or newline
meds_dict = make_meds_dict(as.data.frame(meds_dict_untidy))
meds_dict
# must contain `Drug Name` column
ip.drug.big = bind_rows(antiplatelet, ace_inhibitor, beta_blocker, calcium_channel_blockers, diuretics,
                    statins, system_corticosteroid, antidiabetics, rheumatoids) %>%
  distinct()

ip.drug.big.imputed = impute_meds_w_dict(ip.drug.big, meds_dict) %>%
  select(-`Drug Name`) %>%
  distinct()

# aggregate by HN Number, get 1 if possible
ip.drug.big.imputed = aggregate(ip.drug.big.imputed, by = list(ip.drug.big.imputed[, "Reference Key"]), FUN = "max") %>%
  select(-Group.1)

# no filter section
ip.drug.big.second = bind_rows(mutate(broncodilators, brono = 1), 
                               mutate(cancer, cancer = 1)) %>%
  select(-`Drug Name`) %>%
  distinct()

ip.drug.big.imputed = bind_rows(ip.drug.big.imputed, 
                                ip.drug.big.second)

writexl::write_xlsx(ip.drug.big.imputed, path = "./ip.drug.imputed.xlsx")
```

# ip.dexamethasone
# ip.baricitinib

```{r}
# ----------------
# severe covid-related meds status
# dexamethasone
dexamethasone_shortlist = steroid %>%
  select(`Reference Key`, `Prescription Start Date`, `Drug Name`, `Route`) %>%
  filter(grepl("DEXAMETHASONE", `Drug Name`) & (`Route` %in% c("ORAL","PARENTERAL"))) %>%
  left_join(ip.id,.) %>%
  filter(ymd(`Prescription Start Date`) >= ymd(`Admission Date (yyyy-mm-dd)`) & 
           ymd(`Prescription Start Date`) <= ymd(`Discharge Date (yyyy-mm-dd)`)) %>%
  mutate(daystilldexa = ymd(`Prescription Start Date`) - ymd(`Admission Date (yyyy-mm-dd)`)) %>%
  # get earliest dispension of dexamethasone by reference key
  group_by(`Reference Key`) %>%
  slice(which.min(ymd(`Admission Date (yyyy-mm-dd)`))) %>%
  ungroup()


dexamethasone_shortlist = dexamethasone_shortlist %>%
  select(`Reference Key`, daystilldexa)

# # reference key of patients prescribed dexamethasone
# dexamethasone_idshortlist = dexamethasone_shortlist %>%
#   select(`Reference Key`) %>%
#   distinct()

# # df of HN Number and difference between admission date and prescription date
# dexamethasone_shortlist = dexamethasone_shortlist %>%
#   select(`HN Number`, daystilldexa)

# dexamethasone_shortlist = aggregate(daystilldexa~`Reference Key`, dexamethasone_shortlist, min)
# baricitinib
baricitinib_shortlist = antibodies %>%
  select(`Reference Key`, `Prescription Start Date`, `Drug Name`) %>%
  filter(grepl("BARICITINIB", `Drug Name`)) %>%
  left_join(ip.id,.) %>%
  filter(ymd(`Prescription Start Date`) >= ymd(`Admission Date (yyyy-mm-dd)`) & 
           ymd(`Prescription Start Date`) <= ymd(`Discharge Date (yyyy-mm-dd)`)) %>%
  mutate(daystillbari = ymd(`Prescription Start Date`) - ymd(`Admission Date (yyyy-mm-dd)`)) %>%
  # get earliest dispension of baricitinib by reference key
  group_by(`Reference Key`) %>%
  slice(which.min(ymd(`Admission Date (yyyy-mm-dd)`))) %>%
  ungroup()

baricitinib_shortlist = baricitinib_shortlist %>%
  select(`Reference Key`, daystillbari)
# # reference key of patients prescribed baricitinib
# baricitinibid_shortlist = baricitinib_shortlist %>%
#   # select(`Reference Key`) %>%
#   distinct()

# # df of HN Number and difference between admission date and prescription date
# baricitinib_shortlist = baricitinib_shortlist %>%
#   select(`HN Number`, daystillbari)
# baricitinib_shortlist = aggregate(daystillbari~`Reference Key`, baricitinib_shortlist, min)

writexl::write_xlsx(dexamethasone_shortlist, path = "./ip.dexamethasone.xlsx")
writexl::write_xlsx(baricitinib_shortlist, path = "./ip.baricitinib.xlsx")
```

# medication status of IP epsiodes with IP data only (ip.drug)

```{r}
ip.drug = ip %>%
  # exclude pregnancy
  mutate(pregnancy = ifelse(if_any(diag_cols, ~between(., "630", "679.99")), T, F),
         pregnancy = ifelse(is.na(pregnancy), F, pregnancy)) %>%
  filter(!pregnancy) %>%
  select(-pregnancy) %>%
  select(`Reference Key`, `HN Number`, `Drug Name`, `Admission Date (yyyy-mm-dd)`)
```

# ip.paxlovid: paxlovid, days till paxlovid 

```{r}
# prescription date data
med_dict_paxlovid = tribble(
  ~drug.cat, ~drug.name,
  "paxlovid", "PAXLOVID"
)

# refer to data_import.Rmd for antiviral obj.
pres_date = antiviral %>% 
  select(`Reference Key`, `Dispensing Date (yyyy-mm-dd)`, `Drug Name`)

# refer to IP_data.Rmd for ip.drug obj.
ip.paxlovid = ip.drug %>%
  impute_meds_w_dict(., as.data.frame(med_dict_paxlovid)) %>%
  filter(paxlovid == 1) %>%
  left_join(pres_date)  %>% 
  # by reference key,
  group_by(`Reference Key`) %>%
  # ... get earliest admission
  slice(which.min(ymd(`Admission Date (yyyy-mm-dd)`))) %>%
  # ... get earliest dispension of antiviral
  slice(which.min(ymd(`Dispensing Date (yyyy-mm-dd)`))) %>%
  ungroup()

ip.paxlovid = ip.paxlovid %>%
  mutate(daystillpaxlovid = as.Date(`Dispensing Date (yyyy-mm-dd)`) - 
           as.Date(`Admission Date (yyyy-mm-dd)`)) %>%
  filter(daystillpaxlovid >= 0,
         as.Date(`Dispensing Date (yyyy-mm-dd)`) >= as.Date(`Admission Date (yyyy-mm-dd)`))

ip.paxlovid = ip.paxlovid %>%
  # filter(daystillpaxlovid <= 4)%>%
  select(`Reference Key`, daystillpaxlovid)

ip.paxlovid = ip.paxlovid %>% distinct()

writexl::write_xlsx(ip.paxlovid, path = "./ip.paxlovid.under5d.xlsx")
```

# ip.molnupiravir

```{r}
# prescription date data
med_dict_molnupiravir = tribble(
  ~drug.cat, ~drug.name,
  "molnupiravir", "MOLNUPIRAVIR"
)

ip.molnupiravir = ip.drug %>%
  impute_meds_w_dict(., as.data.frame(med_dict_molnupiravir)) %>%
  filter(molnupiravir == 1) %>%
  left_join(pres_date)  %>% 
  # by reference key,
  group_by(`Reference Key`) %>%
  # ... get earliest admission
  slice(which.min(ymd(`Admission Date (yyyy-mm-dd)`))) %>%
  # ... get earliest dispension of antiviral
  slice(which.min(ymd(`Dispensing Date (yyyy-mm-dd)`))) %>%
  ungroup()

ip.molnupiravir = ip.molnupiravir %>%
  mutate(daystillmolnupiravir = as.Date(`Dispensing Date (yyyy-mm-dd)`) - 
           as.Date(`Admission Date (yyyy-mm-dd)`)) %>%
  filter(daystillmolnupiravir >= 0,
         as.Date(`Dispensing Date (yyyy-mm-dd)`) >= as.Date(`Admission Date (yyyy-mm-dd)`))

ip.molnupiravir = ip.molnupiravir %>%
  # filter(daystillmolnupiravir <= 4)%>%
  select(`Reference Key`, daystillmolnupiravir)

ip.molnupiravir = ip.molnupiravir %>% distinct()

writexl::write_xlsx(ip.molnupiravir, path = "./ip.molnupiravir.under5d.xlsx")
```

# combine all medication status

```{r}
ip.drug.all = ip.drug.big.imputed %>%
  full_join(mutate(dexamethasone_shortlist, dexamethasone = 1)) %>%
  full_join(mutate(baricitinib_shortlist, baricitinib = 1)) %>%
  # full_join(mutate(ip.paxlovid, paxlovid = 1)) %>%
  # full_join(mutate(ip.molnupiravir, molnupiravir = 1)) %>%
  select(-matches("^days"))

ip.drug.all = aggregate(ip.drug.all, by = list(ip.drug.all[, "Reference Key"]), FUN = "max") %>%
  select(-Group.1)
writexl::write_xlsx(ip.drug.all, path = "./ip.drug.all.xlsx")
```

