---
title: "OP_data"
output: html_notebook
---

# import libraries

```{r}
library(tableone)
```

# COVID patients OP data

```{r}
# directory as in onelook drive: ~/COVID Database/Patient-based Record/Designated Clinic
op_drug = read_xlsx_from_folder("./data/Designated Clinic/drug/", ".xlsx")
op_drug = op_drug %>%
  filter(ymd(`Appointment Date (yyyy-mm-dd)`) >= "2022-02-16" & ymd(`Appointment Date (yyyy-mm-dd)`) <= "2022-03-31")
  
op = read_xlsx_from_folder("./data/Designated Clinic/no_frills/", ".xlsx")
op = op %>%
  filter(ymd(`Appointment Date (yyyy-mm-dd)`) >= "2022-02-16" & ymd(`Appointment Date (yyyy-mm-dd)`) <= "2022-03-31")

# demo IP data
demo_ip = read_xlsx_from_folder("./data/5th Wave 202202/", "_demo_IP.xlsx")
```

# check drug names (optional)

```{r}
unique(op_drug$`Drug Name`)[grepl("DEXAMETHASONE", unique(op_drug$`Drug Name`))]
op_drug %>% filter(grepl("DEXAMETHASONE", `Drug Name`))
```


# OP drug use data

```{r}

op_drug = op_drug %>%
  rename(`Drug Name` = `Active Medication - Drug Name`)

colnames(op_drug)

medOPdf = op_drug %>%
  select(`Reference Key`, `OP Number`, `Drug Name`, `Appointment Date (yyyy-mm-dd)`) %>%
  impute_meds(.) %>%
  distinct()

# aggregate by OP Number, get 1 if possible
medOPdf = aggregate(medOPdf, by = list(medOPdf[, "OP Number"]), FUN = "max") %>%
  select(-Group.1)

```


# OP non-drug data

```{r}
op_df = op %>%
  left_join(medOPlist) %>%
  mutate_at(c("paxlovid", "aspirin","ace_inhibitors","beta_blockers","calcium_channel_blockers", "statins","molnupiravir"), ~replace_na(., 0)) %>%
  select(`Age On Appointment (Year)`, Sex, 
         paxlovid, aspirin, ace_inhibitors, beta_blockers, calcium_channel_blockers, statins, molnupiravir) %>%
  mutate(`Age On Appointment (Year)` = as.numeric(`Age On Appointment (Year)`)) %>%
  mutate_at(2:length(colnames(op_df)),factor)
```

# descriptive status by visits

```{r}

op_tab1_p = CreateTableOne(data = op_df, strata = "paxlovid")
op_tab1_p
op_tab1_m = CreateTableOne(data = op_df, strata = "molnupiravir")
op_tab1_m
```

# descriptive stats by patient

```{r}
op_patient = op %>%
  left_join(medOPlist) %>%
  mutate_at(c("paxlovid", "aspirin","ace_inhibitors","beta_blockers","calcium_channel_blockers", "statins","molnupiravir"), ~replace_na(., 0)) %>%
  select(`Reference Key`, `Age On Appointment (Year)`, Sex, 
         paxlovid, aspirin, ace_inhibitors, beta_blockers, calcium_channel_blockers, statins, molnupiravir)

# aggregate by referene key
op_patient = op_patient %>% 
  mutate(`Age On Appointment (Year)` = as.numeric(`Age On Appointment (Year)`)) %>%
  aggregate(op_patient, by = list(op_patient[, "Reference Key"]), FUN = "max") %>%
  select(-Group.1, -`Reference Key`) 
  
op_patient = op_patient %>%
  mutate_at(2:length(colnames(op_patient)), factor)

op_tab1_patient_p = CreateTableOne(data = op_patient, strata = "paxlovid")
op_tab1_patient_p
op_tab1_patient_m = CreateTableOne(data = op_patient, strata = "molnupiravir")
op_tab1_patient_m
```
# OP meds status (deprecated, do not delete)

```{r}
# # ------------------------
# # combine with OP meds status (incomplete)
# # 1. match by reference key &
# # 2. appointment date <= (first) admission date
# medOPdf_shortlist = medOPdf %>%
#   left_join(ip_first_by_patient_id, by = "Reference Key") %>%
#   filter(ymd(`Appointment Date (yyyy-mm-dd)`) <= ymd(`Admission Date (yyyy-mm-dd)`)) %>%
#   select(c("Reference Key", "paxlovid", "aspirin", "ace_inhibitors", "beta_blockers", "calcium_channel_blockers", "statins", "molnupiravir"))
# 
# # combine with administration route info on dexamethasone form steroid
# medIPdf_shortlist = medIPdf %>%
#   left_join(ip_first_by_patient_id, by = "HN Number")
# 
# common_cols = intersect(colnames(medOPdf_shortlist), colnames(medIPdf_shortlist))
# medIOPdf = bind_rows(medOPdf_shortlist %>% select(common_cols), 
#                      medIPdf_shortlist %>% select(c(common_cols, "baricitinib")))

# # aggregate medIOPdf by reference key
# medIOPdf = medIOPdf %>%
#   # as.numeric binary cols
#   mutate_at(2:length(colnames(medIOPdf)), as.numeric)
# medIOPdf =
#   aggregate(medIOPdf, by = list(medIOPdf[, "Reference Key"]), FUN = "max") %>%
#   select(-Group.1) %>%
#   # left-join with dexamethasone meds status 
#   mutate(dexamethasone = ifelse(`Reference Key` %in% dexamethasone_idshortlist$`Reference Key`, 1, 0)) %>%
#   mutate_at(2:length(colnames(medIOPdf)), ~replace_na(., "0")) %>%
#   # as.factor binary cols
#   mutate_at(2:length(colnames(medIOPdf)), factor) 
#   
# 
# writexl::write_xlsx(medIOPdf, "./medIOPdf.xlsx")
```
